title: Stackbit Exto Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
color_scheme: light
accent_color: pink
header:
  title: Dauerbaum®
  has_nav: true
  nav_links:
    - label: Baumplege
      url: /
      style: link
    - label: Über
      url: /portfolio/
      style: link
    - label: Kontakt
      url: /blog/
      style: link
    - label: About
      url: /about/
      style: link
    - label: Über
      url: /contact/
      style: link
footer:
  content: >-
    &copy; Stackbit. All rights reserved. This Jamstack site was created with <a
    href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
    rel="noopener">Stackbit</a>. Create yours <a
    href="https://app.stackbit.com/create?theme=exto&utm_source=deployed-footer"
    target="_blank" rel="noopener">now</a>
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      style: icon
      icon: twitter
      new_window: true
    - label: Instagram
      url: 'https://www.instagram.com/'
      style: icon
      icon: instagram
      new_window: true
    - label: Dribbble
      url: 'https://dribbble.com/'
      style: icon
      icon: dribbble
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: icon
      icon: linkedin
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https://beige-pluto-df7b5.netlify.app'
